//> using publish.organization "io.github.alexarchambault.scala-cli.workflow"
//> using publish.name "workflow"
//> using publish.computeVersion "git:tag"
//> using publish.repository "central-s01"
//> using publish.user "env:PUBLISH_USER"
//> using publish.password "env:PUBLISH_PASSWORD"
//> using publish.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/scala-cli/default-workflow"
//> using publish.versionControl "github:scala-cli/default-workflow"
//> using publish.developer "alexarchambault|Alex Archambault|https://github.com/alexarchambault"
